// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package repository

import (
	"context"

	"github.com/0xpelamar/kingscomp/internal/entity"
	mock "github.com/stretchr/testify/mock"
)

// NewMockCommonBehaviour creates a new instance of MockCommonBehaviour. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCommonBehaviour[T entity.Entity](t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCommonBehaviour[T] {
	mock := &MockCommonBehaviour[T]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCommonBehaviour is an autogenerated mock type for the CommonBehaviour type
type MockCommonBehaviour[T entity.Entity] struct {
	mock.Mock
}

type MockCommonBehaviour_Expecter[T entity.Entity] struct {
	mock *mock.Mock
}

func (_m *MockCommonBehaviour[T]) EXPECT() *MockCommonBehaviour_Expecter[T] {
	return &MockCommonBehaviour_Expecter[T]{mock: &_m.Mock}
}

// Get provides a mock function for the type MockCommonBehaviour
func (_mock *MockCommonBehaviour[T]) Get(context1 context.Context, iD entity.ID) (T, error) {
	ret := _mock.Called(context1, iD)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 T
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.ID) (T, error)); ok {
		return returnFunc(context1, iD)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.ID) T); ok {
		r0 = returnFunc(context1, iD)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(T)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, entity.ID) error); ok {
		r1 = returnFunc(context1, iD)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCommonBehaviour_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockCommonBehaviour_Get_Call[T entity.Entity] struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - context1 context.Context
//   - iD entity.ID
func (_e *MockCommonBehaviour_Expecter[T]) Get(context1 any, iD any) *MockCommonBehaviour_Get_Call[T] {
	return &MockCommonBehaviour_Get_Call[T]{Call: _e.mock.On("Get", context1, iD)}
}

func (_c *MockCommonBehaviour_Get_Call[T]) Run(run func(context1 context.Context, iD entity.ID)) *MockCommonBehaviour_Get_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 entity.ID
		if args[1] != nil {
			arg1 = args[1].(entity.ID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCommonBehaviour_Get_Call[T]) Return(v T, err error) *MockCommonBehaviour_Get_Call[T] {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockCommonBehaviour_Get_Call[T]) RunAndReturn(run func(context1 context.Context, iD entity.ID) (T, error)) *MockCommonBehaviour_Get_Call[T] {
	_c.Call.Return(run)
	return _c
}

// MGet provides a mock function for the type MockCommonBehaviour
func (_mock *MockCommonBehaviour[T]) MGet(ctx context.Context, IDs ...entity.ID) ([]T, error) {
	var tmpRet mock.Arguments
	if len(IDs) > 0 {
		tmpRet = _mock.Called(ctx, IDs)
	} else {
		tmpRet = _mock.Called(ctx)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for MGet")
	}

	var r0 []T
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...entity.ID) ([]T, error)); ok {
		return returnFunc(ctx, IDs...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...entity.ID) []T); ok {
		r0 = returnFunc(ctx, IDs...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]T)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ...entity.ID) error); ok {
		r1 = returnFunc(ctx, IDs...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCommonBehaviour_MGet_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MGet'
type MockCommonBehaviour_MGet_Call[T entity.Entity] struct {
	*mock.Call
}

// MGet is a helper method to define mock.On call
//   - ctx context.Context
//   - IDs ...entity.ID
func (_e *MockCommonBehaviour_Expecter[T]) MGet(ctx any, IDs ...any) *MockCommonBehaviour_MGet_Call[T] {
	return &MockCommonBehaviour_MGet_Call[T]{Call: _e.mock.On("MGet",
		append([]any{ctx}, IDs...)...)}
}

func (_c *MockCommonBehaviour_MGet_Call[T]) Run(run func(ctx context.Context, IDs ...entity.ID)) *MockCommonBehaviour_MGet_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []entity.ID
		var variadicArgs []entity.ID
		if len(args) > 1 {
			variadicArgs = args[1].([]entity.ID)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockCommonBehaviour_MGet_Call[T]) Return(vs []T, err error) *MockCommonBehaviour_MGet_Call[T] {
	_c.Call.Return(vs, err)
	return _c
}

func (_c *MockCommonBehaviour_MGet_Call[T]) RunAndReturn(run func(ctx context.Context, IDs ...entity.ID) ([]T, error)) *MockCommonBehaviour_MGet_Call[T] {
	_c.Call.Return(run)
	return _c
}

// MSet provides a mock function for the type MockCommonBehaviour
func (_mock *MockCommonBehaviour[T]) MSet(ctx context.Context, entities ...T) error {
	var tmpRet mock.Arguments
	if len(entities) > 0 {
		tmpRet = _mock.Called(ctx, entities)
	} else {
		tmpRet = _mock.Called(ctx)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for MSet")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...T) error); ok {
		r0 = returnFunc(ctx, entities...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCommonBehaviour_MSet_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MSet'
type MockCommonBehaviour_MSet_Call[T entity.Entity] struct {
	*mock.Call
}

// MSet is a helper method to define mock.On call
//   - ctx context.Context
//   - entities ...T
func (_e *MockCommonBehaviour_Expecter[T]) MSet(ctx any, entities ...any) *MockCommonBehaviour_MSet_Call[T] {
	return &MockCommonBehaviour_MSet_Call[T]{Call: _e.mock.On("MSet",
		append([]any{ctx}, entities...)...)}
}

func (_c *MockCommonBehaviour_MSet_Call[T]) Run(run func(ctx context.Context, entities ...T)) *MockCommonBehaviour_MSet_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []T
		var variadicArgs []T
		if len(args) > 1 {
			variadicArgs = args[1].([]T)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockCommonBehaviour_MSet_Call[T]) Return(err error) *MockCommonBehaviour_MSet_Call[T] {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCommonBehaviour_MSet_Call[T]) RunAndReturn(run func(ctx context.Context, entities ...T) error) *MockCommonBehaviour_MSet_Call[T] {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type MockCommonBehaviour
func (_mock *MockCommonBehaviour[T]) Save(context1 context.Context, v T) error {
	ret := _mock.Called(context1, v)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, T) error); ok {
		r0 = returnFunc(context1, v)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCommonBehaviour_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockCommonBehaviour_Save_Call[T entity.Entity] struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - context1 context.Context
//   - v T
func (_e *MockCommonBehaviour_Expecter[T]) Save(context1 any, v any) *MockCommonBehaviour_Save_Call[T] {
	return &MockCommonBehaviour_Save_Call[T]{Call: _e.mock.On("Save", context1, v)}
}

func (_c *MockCommonBehaviour_Save_Call[T]) Run(run func(context1 context.Context, v T)) *MockCommonBehaviour_Save_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 T
		if args[1] != nil {
			arg1 = args[1].(T)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCommonBehaviour_Save_Call[T]) Return(err error) *MockCommonBehaviour_Save_Call[T] {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCommonBehaviour_Save_Call[T]) RunAndReturn(run func(context1 context.Context, v T) error) *MockCommonBehaviour_Save_Call[T] {
	_c.Call.Return(run)
	return _c
}

// NewMockAccount creates a new instance of MockAccount. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAccount(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAccount {
	mock := &MockAccount{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAccount is an autogenerated mock type for the Account type
type MockAccount struct {
	mock.Mock
}

type MockAccount_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAccount) EXPECT() *MockAccount_Expecter {
	return &MockAccount_Expecter{mock: &_m.Mock}
}

// Get provides a mock function for the type MockAccount
func (_mock *MockAccount) Get(context1 context.Context, iD entity.ID) (entity.Account, error) {
	ret := _mock.Called(context1, iD)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 entity.Account
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.ID) (entity.Account, error)); ok {
		return returnFunc(context1, iD)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.ID) entity.Account); ok {
		r0 = returnFunc(context1, iD)
	} else {
		r0 = ret.Get(0).(entity.Account)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, entity.ID) error); ok {
		r1 = returnFunc(context1, iD)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAccount_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockAccount_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - context1 context.Context
//   - iD entity.ID
func (_e *MockAccount_Expecter) Get(context1 any, iD any) *MockAccount_Get_Call {
	return &MockAccount_Get_Call{Call: _e.mock.On("Get", context1, iD)}
}

func (_c *MockAccount_Get_Call) Run(run func(context1 context.Context, iD entity.ID)) *MockAccount_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 entity.ID
		if args[1] != nil {
			arg1 = args[1].(entity.ID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAccount_Get_Call) Return(account entity.Account, err error) *MockAccount_Get_Call {
	_c.Call.Return(account, err)
	return _c
}

func (_c *MockAccount_Get_Call) RunAndReturn(run func(context1 context.Context, iD entity.ID) (entity.Account, error)) *MockAccount_Get_Call {
	_c.Call.Return(run)
	return _c
}

// MGet provides a mock function for the type MockAccount
func (_mock *MockAccount) MGet(ctx context.Context, IDs ...entity.ID) ([]entity.Account, error) {
	var tmpRet mock.Arguments
	if len(IDs) > 0 {
		tmpRet = _mock.Called(ctx, IDs)
	} else {
		tmpRet = _mock.Called(ctx)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for MGet")
	}

	var r0 []entity.Account
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...entity.ID) ([]entity.Account, error)); ok {
		return returnFunc(ctx, IDs...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...entity.ID) []entity.Account); ok {
		r0 = returnFunc(ctx, IDs...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Account)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ...entity.ID) error); ok {
		r1 = returnFunc(ctx, IDs...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAccount_MGet_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MGet'
type MockAccount_MGet_Call struct {
	*mock.Call
}

// MGet is a helper method to define mock.On call
//   - ctx context.Context
//   - IDs ...entity.ID
func (_e *MockAccount_Expecter) MGet(ctx any, IDs ...any) *MockAccount_MGet_Call {
	return &MockAccount_MGet_Call{Call: _e.mock.On("MGet",
		append([]any{ctx}, IDs...)...)}
}

func (_c *MockAccount_MGet_Call) Run(run func(ctx context.Context, IDs ...entity.ID)) *MockAccount_MGet_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []entity.ID
		var variadicArgs []entity.ID
		if len(args) > 1 {
			variadicArgs = args[1].([]entity.ID)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockAccount_MGet_Call) Return(accounts []entity.Account, err error) *MockAccount_MGet_Call {
	_c.Call.Return(accounts, err)
	return _c
}

func (_c *MockAccount_MGet_Call) RunAndReturn(run func(ctx context.Context, IDs ...entity.ID) ([]entity.Account, error)) *MockAccount_MGet_Call {
	_c.Call.Return(run)
	return _c
}

// MSet provides a mock function for the type MockAccount
func (_mock *MockAccount) MSet(ctx context.Context, entities ...entity.Account) error {
	var tmpRet mock.Arguments
	if len(entities) > 0 {
		tmpRet = _mock.Called(ctx, entities)
	} else {
		tmpRet = _mock.Called(ctx)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for MSet")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...entity.Account) error); ok {
		r0 = returnFunc(ctx, entities...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAccount_MSet_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MSet'
type MockAccount_MSet_Call struct {
	*mock.Call
}

// MSet is a helper method to define mock.On call
//   - ctx context.Context
//   - entities ...entity.Account
func (_e *MockAccount_Expecter) MSet(ctx any, entities ...any) *MockAccount_MSet_Call {
	return &MockAccount_MSet_Call{Call: _e.mock.On("MSet",
		append([]any{ctx}, entities...)...)}
}

func (_c *MockAccount_MSet_Call) Run(run func(ctx context.Context, entities ...entity.Account)) *MockAccount_MSet_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []entity.Account
		var variadicArgs []entity.Account
		if len(args) > 1 {
			variadicArgs = args[1].([]entity.Account)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockAccount_MSet_Call) Return(err error) *MockAccount_MSet_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAccount_MSet_Call) RunAndReturn(run func(ctx context.Context, entities ...entity.Account) error) *MockAccount_MSet_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type MockAccount
func (_mock *MockAccount) Save(context1 context.Context, account entity.Account) error {
	ret := _mock.Called(context1, account)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.Account) error); ok {
		r0 = returnFunc(context1, account)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAccount_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockAccount_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - context1 context.Context
//   - account entity.Account
func (_e *MockAccount_Expecter) Save(context1 any, account any) *MockAccount_Save_Call {
	return &MockAccount_Save_Call{Call: _e.mock.On("Save", context1, account)}
}

func (_c *MockAccount_Save_Call) Run(run func(context1 context.Context, account entity.Account)) *MockAccount_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 entity.Account
		if args[1] != nil {
			arg1 = args[1].(entity.Account)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAccount_Save_Call) Return(err error) *MockAccount_Save_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAccount_Save_Call) RunAndReturn(run func(context1 context.Context, account entity.Account) error) *MockAccount_Save_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockLobby creates a new instance of MockLobby. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLobby(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLobby {
	mock := &MockLobby{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockLobby is an autogenerated mock type for the Lobby type
type MockLobby struct {
	mock.Mock
}

type MockLobby_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLobby) EXPECT() *MockLobby_Expecter {
	return &MockLobby_Expecter{mock: &_m.Mock}
}

// Get provides a mock function for the type MockLobby
func (_mock *MockLobby) Get(context1 context.Context, iD entity.ID) (entity.Lobby, error) {
	ret := _mock.Called(context1, iD)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 entity.Lobby
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.ID) (entity.Lobby, error)); ok {
		return returnFunc(context1, iD)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.ID) entity.Lobby); ok {
		r0 = returnFunc(context1, iD)
	} else {
		r0 = ret.Get(0).(entity.Lobby)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, entity.ID) error); ok {
		r1 = returnFunc(context1, iD)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLobby_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockLobby_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - context1 context.Context
//   - iD entity.ID
func (_e *MockLobby_Expecter) Get(context1 any, iD any) *MockLobby_Get_Call {
	return &MockLobby_Get_Call{Call: _e.mock.On("Get", context1, iD)}
}

func (_c *MockLobby_Get_Call) Run(run func(context1 context.Context, iD entity.ID)) *MockLobby_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 entity.ID
		if args[1] != nil {
			arg1 = args[1].(entity.ID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockLobby_Get_Call) Return(lobby entity.Lobby, err error) *MockLobby_Get_Call {
	_c.Call.Return(lobby, err)
	return _c
}

func (_c *MockLobby_Get_Call) RunAndReturn(run func(context1 context.Context, iD entity.ID) (entity.Lobby, error)) *MockLobby_Get_Call {
	_c.Call.Return(run)
	return _c
}

// LobbyPlayers provides a mock function for the type MockLobby
func (_mock *MockLobby) LobbyPlayers(ctx context.Context, LobbyID entity.ID) ([]entity.Account, error) {
	ret := _mock.Called(ctx, LobbyID)

	if len(ret) == 0 {
		panic("no return value specified for LobbyPlayers")
	}

	var r0 []entity.Account
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.ID) ([]entity.Account, error)); ok {
		return returnFunc(ctx, LobbyID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.ID) []entity.Account); ok {
		r0 = returnFunc(ctx, LobbyID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Account)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, entity.ID) error); ok {
		r1 = returnFunc(ctx, LobbyID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLobby_LobbyPlayers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LobbyPlayers'
type MockLobby_LobbyPlayers_Call struct {
	*mock.Call
}

// LobbyPlayers is a helper method to define mock.On call
//   - ctx context.Context
//   - LobbyID entity.ID
func (_e *MockLobby_Expecter) LobbyPlayers(ctx any, LobbyID any) *MockLobby_LobbyPlayers_Call {
	return &MockLobby_LobbyPlayers_Call{Call: _e.mock.On("LobbyPlayers", ctx, LobbyID)}
}

func (_c *MockLobby_LobbyPlayers_Call) Run(run func(ctx context.Context, LobbyID entity.ID)) *MockLobby_LobbyPlayers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 entity.ID
		if args[1] != nil {
			arg1 = args[1].(entity.ID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockLobby_LobbyPlayers_Call) Return(accounts []entity.Account, err error) *MockLobby_LobbyPlayers_Call {
	_c.Call.Return(accounts, err)
	return _c
}

func (_c *MockLobby_LobbyPlayers_Call) RunAndReturn(run func(ctx context.Context, LobbyID entity.ID) ([]entity.Account, error)) *MockLobby_LobbyPlayers_Call {
	_c.Call.Return(run)
	return _c
}

// MGet provides a mock function for the type MockLobby
func (_mock *MockLobby) MGet(ctx context.Context, IDs ...entity.ID) ([]entity.Lobby, error) {
	var tmpRet mock.Arguments
	if len(IDs) > 0 {
		tmpRet = _mock.Called(ctx, IDs)
	} else {
		tmpRet = _mock.Called(ctx)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for MGet")
	}

	var r0 []entity.Lobby
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...entity.ID) ([]entity.Lobby, error)); ok {
		return returnFunc(ctx, IDs...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...entity.ID) []entity.Lobby); ok {
		r0 = returnFunc(ctx, IDs...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Lobby)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ...entity.ID) error); ok {
		r1 = returnFunc(ctx, IDs...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLobby_MGet_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MGet'
type MockLobby_MGet_Call struct {
	*mock.Call
}

// MGet is a helper method to define mock.On call
//   - ctx context.Context
//   - IDs ...entity.ID
func (_e *MockLobby_Expecter) MGet(ctx any, IDs ...any) *MockLobby_MGet_Call {
	return &MockLobby_MGet_Call{Call: _e.mock.On("MGet",
		append([]any{ctx}, IDs...)...)}
}

func (_c *MockLobby_MGet_Call) Run(run func(ctx context.Context, IDs ...entity.ID)) *MockLobby_MGet_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []entity.ID
		var variadicArgs []entity.ID
		if len(args) > 1 {
			variadicArgs = args[1].([]entity.ID)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockLobby_MGet_Call) Return(lobbys []entity.Lobby, err error) *MockLobby_MGet_Call {
	_c.Call.Return(lobbys, err)
	return _c
}

func (_c *MockLobby_MGet_Call) RunAndReturn(run func(ctx context.Context, IDs ...entity.ID) ([]entity.Lobby, error)) *MockLobby_MGet_Call {
	_c.Call.Return(run)
	return _c
}

// MSet provides a mock function for the type MockLobby
func (_mock *MockLobby) MSet(ctx context.Context, entities ...entity.Lobby) error {
	var tmpRet mock.Arguments
	if len(entities) > 0 {
		tmpRet = _mock.Called(ctx, entities)
	} else {
		tmpRet = _mock.Called(ctx)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for MSet")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...entity.Lobby) error); ok {
		r0 = returnFunc(ctx, entities...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockLobby_MSet_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MSet'
type MockLobby_MSet_Call struct {
	*mock.Call
}

// MSet is a helper method to define mock.On call
//   - ctx context.Context
//   - entities ...entity.Lobby
func (_e *MockLobby_Expecter) MSet(ctx any, entities ...any) *MockLobby_MSet_Call {
	return &MockLobby_MSet_Call{Call: _e.mock.On("MSet",
		append([]any{ctx}, entities...)...)}
}

func (_c *MockLobby_MSet_Call) Run(run func(ctx context.Context, entities ...entity.Lobby)) *MockLobby_MSet_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []entity.Lobby
		var variadicArgs []entity.Lobby
		if len(args) > 1 {
			variadicArgs = args[1].([]entity.Lobby)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockLobby_MSet_Call) Return(err error) *MockLobby_MSet_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockLobby_MSet_Call) RunAndReturn(run func(ctx context.Context, entities ...entity.Lobby) error) *MockLobby_MSet_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type MockLobby
func (_mock *MockLobby) Save(context1 context.Context, lobby entity.Lobby) error {
	ret := _mock.Called(context1, lobby)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.Lobby) error); ok {
		r0 = returnFunc(context1, lobby)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockLobby_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockLobby_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - context1 context.Context
//   - lobby entity.Lobby
func (_e *MockLobby_Expecter) Save(context1 any, lobby any) *MockLobby_Save_Call {
	return &MockLobby_Save_Call{Call: _e.mock.On("Save", context1, lobby)}
}

func (_c *MockLobby_Save_Call) Run(run func(context1 context.Context, lobby entity.Lobby)) *MockLobby_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 entity.Lobby
		if args[1] != nil {
			arg1 = args[1].(entity.Lobby)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockLobby_Save_Call) Return(err error) *MockLobby_Save_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockLobby_Save_Call) RunAndReturn(run func(context1 context.Context, lobby entity.Lobby) error) *MockLobby_Save_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockQuestion creates a new instance of MockQuestion. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockQuestion(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockQuestion {
	mock := &MockQuestion{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockQuestion is an autogenerated mock type for the Question type
type MockQuestion struct {
	mock.Mock
}

type MockQuestion_Expecter struct {
	mock *mock.Mock
}

func (_m *MockQuestion) EXPECT() *MockQuestion_Expecter {
	return &MockQuestion_Expecter{mock: &_m.Mock}
}

// Get provides a mock function for the type MockQuestion
func (_mock *MockQuestion) Get(context1 context.Context, iD entity.ID) (entity.Question, error) {
	ret := _mock.Called(context1, iD)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 entity.Question
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.ID) (entity.Question, error)); ok {
		return returnFunc(context1, iD)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.ID) entity.Question); ok {
		r0 = returnFunc(context1, iD)
	} else {
		r0 = ret.Get(0).(entity.Question)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, entity.ID) error); ok {
		r1 = returnFunc(context1, iD)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQuestion_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockQuestion_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - context1 context.Context
//   - iD entity.ID
func (_e *MockQuestion_Expecter) Get(context1 any, iD any) *MockQuestion_Get_Call {
	return &MockQuestion_Get_Call{Call: _e.mock.On("Get", context1, iD)}
}

func (_c *MockQuestion_Get_Call) Run(run func(context1 context.Context, iD entity.ID)) *MockQuestion_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 entity.ID
		if args[1] != nil {
			arg1 = args[1].(entity.ID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQuestion_Get_Call) Return(question entity.Question, err error) *MockQuestion_Get_Call {
	_c.Call.Return(question, err)
	return _c
}

func (_c *MockQuestion_Get_Call) RunAndReturn(run func(context1 context.Context, iD entity.ID) (entity.Question, error)) *MockQuestion_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetActiveQuestions provides a mock function for the type MockQuestion
func (_mock *MockQuestion) GetActiveQuestions(ctx context.Context, index ...int64) ([]entity.Question, error) {
	var tmpRet mock.Arguments
	if len(index) > 0 {
		tmpRet = _mock.Called(ctx, index)
	} else {
		tmpRet = _mock.Called(ctx)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for GetActiveQuestions")
	}

	var r0 []entity.Question
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...int64) ([]entity.Question, error)); ok {
		return returnFunc(ctx, index...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...int64) []entity.Question); ok {
		r0 = returnFunc(ctx, index...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Question)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ...int64) error); ok {
		r1 = returnFunc(ctx, index...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQuestion_GetActiveQuestions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetActiveQuestions'
type MockQuestion_GetActiveQuestions_Call struct {
	*mock.Call
}

// GetActiveQuestions is a helper method to define mock.On call
//   - ctx context.Context
//   - index ...int64
func (_e *MockQuestion_Expecter) GetActiveQuestions(ctx any, index ...any) *MockQuestion_GetActiveQuestions_Call {
	return &MockQuestion_GetActiveQuestions_Call{Call: _e.mock.On("GetActiveQuestions",
		append([]any{ctx}, index...)...)}
}

func (_c *MockQuestion_GetActiveQuestions_Call) Run(run func(ctx context.Context, index ...int64)) *MockQuestion_GetActiveQuestions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []int64
		var variadicArgs []int64
		if len(args) > 1 {
			variadicArgs = args[1].([]int64)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockQuestion_GetActiveQuestions_Call) Return(questions []entity.Question, err error) *MockQuestion_GetActiveQuestions_Call {
	_c.Call.Return(questions, err)
	return _c
}

func (_c *MockQuestion_GetActiveQuestions_Call) RunAndReturn(run func(ctx context.Context, index ...int64) ([]entity.Question, error)) *MockQuestion_GetActiveQuestions_Call {
	_c.Call.Return(run)
	return _c
}

// GetActiveQuestionsCount provides a mock function for the type MockQuestion
func (_mock *MockQuestion) GetActiveQuestionsCount(ctx context.Context) (int64, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetActiveQuestionsCount")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (int64, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) int64); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQuestion_GetActiveQuestionsCount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetActiveQuestionsCount'
type MockQuestion_GetActiveQuestionsCount_Call struct {
	*mock.Call
}

// GetActiveQuestionsCount is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockQuestion_Expecter) GetActiveQuestionsCount(ctx any) *MockQuestion_GetActiveQuestionsCount_Call {
	return &MockQuestion_GetActiveQuestionsCount_Call{Call: _e.mock.On("GetActiveQuestionsCount", ctx)}
}

func (_c *MockQuestion_GetActiveQuestionsCount_Call) Run(run func(ctx context.Context)) *MockQuestion_GetActiveQuestionsCount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockQuestion_GetActiveQuestionsCount_Call) Return(n int64, err error) *MockQuestion_GetActiveQuestionsCount_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockQuestion_GetActiveQuestionsCount_Call) RunAndReturn(run func(ctx context.Context) (int64, error)) *MockQuestion_GetActiveQuestionsCount_Call {
	_c.Call.Return(run)
	return _c
}

// MGet provides a mock function for the type MockQuestion
func (_mock *MockQuestion) MGet(ctx context.Context, IDs ...entity.ID) ([]entity.Question, error) {
	var tmpRet mock.Arguments
	if len(IDs) > 0 {
		tmpRet = _mock.Called(ctx, IDs)
	} else {
		tmpRet = _mock.Called(ctx)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for MGet")
	}

	var r0 []entity.Question
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...entity.ID) ([]entity.Question, error)); ok {
		return returnFunc(ctx, IDs...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...entity.ID) []entity.Question); ok {
		r0 = returnFunc(ctx, IDs...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Question)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ...entity.ID) error); ok {
		r1 = returnFunc(ctx, IDs...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQuestion_MGet_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MGet'
type MockQuestion_MGet_Call struct {
	*mock.Call
}

// MGet is a helper method to define mock.On call
//   - ctx context.Context
//   - IDs ...entity.ID
func (_e *MockQuestion_Expecter) MGet(ctx any, IDs ...any) *MockQuestion_MGet_Call {
	return &MockQuestion_MGet_Call{Call: _e.mock.On("MGet",
		append([]any{ctx}, IDs...)...)}
}

func (_c *MockQuestion_MGet_Call) Run(run func(ctx context.Context, IDs ...entity.ID)) *MockQuestion_MGet_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []entity.ID
		var variadicArgs []entity.ID
		if len(args) > 1 {
			variadicArgs = args[1].([]entity.ID)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockQuestion_MGet_Call) Return(questions []entity.Question, err error) *MockQuestion_MGet_Call {
	_c.Call.Return(questions, err)
	return _c
}

func (_c *MockQuestion_MGet_Call) RunAndReturn(run func(ctx context.Context, IDs ...entity.ID) ([]entity.Question, error)) *MockQuestion_MGet_Call {
	_c.Call.Return(run)
	return _c
}

// MSet provides a mock function for the type MockQuestion
func (_mock *MockQuestion) MSet(ctx context.Context, entities ...entity.Question) error {
	var tmpRet mock.Arguments
	if len(entities) > 0 {
		tmpRet = _mock.Called(ctx, entities)
	} else {
		tmpRet = _mock.Called(ctx)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for MSet")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...entity.Question) error); ok {
		r0 = returnFunc(ctx, entities...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockQuestion_MSet_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MSet'
type MockQuestion_MSet_Call struct {
	*mock.Call
}

// MSet is a helper method to define mock.On call
//   - ctx context.Context
//   - entities ...entity.Question
func (_e *MockQuestion_Expecter) MSet(ctx any, entities ...any) *MockQuestion_MSet_Call {
	return &MockQuestion_MSet_Call{Call: _e.mock.On("MSet",
		append([]any{ctx}, entities...)...)}
}

func (_c *MockQuestion_MSet_Call) Run(run func(ctx context.Context, entities ...entity.Question)) *MockQuestion_MSet_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []entity.Question
		var variadicArgs []entity.Question
		if len(args) > 1 {
			variadicArgs = args[1].([]entity.Question)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockQuestion_MSet_Call) Return(err error) *MockQuestion_MSet_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockQuestion_MSet_Call) RunAndReturn(run func(ctx context.Context, entities ...entity.Question) error) *MockQuestion_MSet_Call {
	_c.Call.Return(run)
	return _c
}

// PushActiveQuestion provides a mock function for the type MockQuestion
func (_mock *MockQuestion) PushActiveQuestion(ctx context.Context, questions ...entity.Question) error {
	var tmpRet mock.Arguments
	if len(questions) > 0 {
		tmpRet = _mock.Called(ctx, questions)
	} else {
		tmpRet = _mock.Called(ctx)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for PushActiveQuestion")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...entity.Question) error); ok {
		r0 = returnFunc(ctx, questions...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockQuestion_PushActiveQuestion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PushActiveQuestion'
type MockQuestion_PushActiveQuestion_Call struct {
	*mock.Call
}

// PushActiveQuestion is a helper method to define mock.On call
//   - ctx context.Context
//   - questions ...entity.Question
func (_e *MockQuestion_Expecter) PushActiveQuestion(ctx any, questions ...any) *MockQuestion_PushActiveQuestion_Call {
	return &MockQuestion_PushActiveQuestion_Call{Call: _e.mock.On("PushActiveQuestion",
		append([]any{ctx}, questions...)...)}
}

func (_c *MockQuestion_PushActiveQuestion_Call) Run(run func(ctx context.Context, questions ...entity.Question)) *MockQuestion_PushActiveQuestion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []entity.Question
		var variadicArgs []entity.Question
		if len(args) > 1 {
			variadicArgs = args[1].([]entity.Question)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockQuestion_PushActiveQuestion_Call) Return(err error) *MockQuestion_PushActiveQuestion_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockQuestion_PushActiveQuestion_Call) RunAndReturn(run func(ctx context.Context, questions ...entity.Question) error) *MockQuestion_PushActiveQuestion_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type MockQuestion
func (_mock *MockQuestion) Save(context1 context.Context, question entity.Question) error {
	ret := _mock.Called(context1, question)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.Question) error); ok {
		r0 = returnFunc(context1, question)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockQuestion_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockQuestion_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - context1 context.Context
//   - question entity.Question
func (_e *MockQuestion_Expecter) Save(context1 any, question any) *MockQuestion_Save_Call {
	return &MockQuestion_Save_Call{Call: _e.mock.On("Save", context1, question)}
}

func (_c *MockQuestion_Save_Call) Run(run func(context1 context.Context, question entity.Question)) *MockQuestion_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 entity.Question
		if args[1] != nil {
			arg1 = args[1].(entity.Question)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQuestion_Save_Call) Return(err error) *MockQuestion_Save_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockQuestion_Save_Call) RunAndReturn(run func(context1 context.Context, question entity.Question) error) *MockQuestion_Save_Call {
	_c.Call.Return(run)
	return _c
}
